"""
Collect demonstration episodes from the MuJoCo scene into LeRobot dataset
format, ready for `lerobot-train --policy.path=lerobot/smolvla_base ...`.

Trajectories are generated by IK (mink), not sine sweeps: for each training
seed, `build_drawer_and_cutlery_episode` reads where DomainRandomizer actually
placed the drawer and objects, solves IK to those real coordinates, and
returns a joint-space trajectory. No manual per-seed tuning.

Seed discipline: episodes are recorded using ONLY seeds from
randomization.yaml `training.seed_range` -- never the 10 reserved eval seeds.
"""
import os
os.environ["SVT_LOG"] = "0"
import sys
import numpy as np
import mujoco
from lerobot.datasets.lerobot_dataset import LeRobotDataset


sys.path.insert(0, "sim")
sys.path.insert(0, ".")
from randomization import DomainRandomizer  # noqa: E402
from scripted_episode_ik import build_drawer_and_cutlery_episode  # noqa: E402
from ik_demo_utils import (  # noqa: E402
    activate_grasp_connect, deactivate_grasp_connect,
    activate_grasp_weld, deactivate_grasp_weld,
)

MODEL_PATH = "sim/assets/dinner_table_dual_so101.xml"
RANDOMIZATION_CFG = "configs/randomization.yaml"
FPS = 30

# Render every Nth simulation step. Halves recording time; SmolVLA downsamples
# images anyway, so 15 fps output is fine for training.
RENDER_EVERY_N_STEPS = 2

ACTUATOR_NAMES = [
    "left_shoulder_pan",
    "left_shoulder_lift",
    "left_elbow_flex",
    "left_wrist_flex",
    "left_wrist_roll",
    "left_gripper",
    "right_shoulder_pan",
    "right_shoulder_lift",
    "right_elbow_flex",
    "right_wrist_flex",
    "right_wrist_roll",
    "right_gripper",
]

CAMERA_SPECS = {
    "overhead": (320, 240),
    "wrist_left": (160, 120),
    "wrist_right": (160, 120),
}


def build_features():
    features = {
        "action": {
            "dtype": "float32",
            "shape": (len(ACTUATOR_NAMES),),
            "names": ACTUATOR_NAMES,
        },
        "observation.state": {
            "dtype": "float32",
            "shape": (len(ACTUATOR_NAMES),),
            "names": ACTUATOR_NAMES,
        },
    }
    for cam_name, (w, h) in CAMERA_SPECS.items():
        features[f"observation.images.{cam_name}"] = {
            "dtype": "video",
            "shape": (h, w, 3),
            "names": ["height", "width", "channels"],
        }
    return features


def get_joint_state(model, data):
    state = np.zeros(len(ACTUATOR_NAMES), dtype=np.float32)
    for i, act_name in enumerate(ACTUATOR_NAMES):
        act_id = model.actuator(act_name).id
        joint_id = model.actuator_trnid[act_id, 0]
        qpos_adr = model.jnt_qposadr[joint_id]
        state[i] = data.qpos[qpos_adr]
    return state


def render_all_cameras(renderers, data):
    frames = {}
    for cam_name, renderer in renderers.items():
        renderer.update_scene(data, camera=cam_name)
        frames[cam_name] = renderer.render()
    return frames


def _apply_qpos_to_ctrl(model, data, qpos):
    """Write IK qpos to actuators, EXCEPT the grippers.

    Gripper commands come exclusively from gripper_trace, which knows which
    side (left/right) is active per step. Writing gripper ctrl from qpos
    here would let stale IK-solved hinge values stomp on the real open/closed
    command -- that is why both gripper names are skipped.
    """
    for act_name in ACTUATOR_NAMES:
        if act_name.endswith("_gripper"):
            continue
        act_id = model.actuator(act_name).id
        joint_id = model.actuator_trnid[act_id, 0]
        qpos_adr = model.jnt_qposadr[joint_id]
        data.ctrl[act_id] = qpos[qpos_adr]


def _find_plate_release_step(gripper_trace):
    """Return the control-step index where the LEFT gripper transitions from
    closed (<0) to open (>0). That is the moment the plate is put down and
    the weld constraint must be released. Returns None if the gripper never
    reopens (which is the case when the episode ends while still holding the
    plate -- the release then simply never fires, which is fine, the weld
    stays active to the end of the recorded trajectory).

    Mirrors the identical scan in test_phases.py so both code paths find the
    same event.
    """
    prev_left_val = None
    for i, g in enumerate(gripper_trace):
        if g is None:
            continue
        side, val = g
        if side != "left":
            continue
        if prev_left_val is not None and prev_left_val < 0.0 and val > 0.0:
            return i
        prev_left_val = val
    return None


def collect(n_episodes, repo_id, root, instruction, control_decimation=10, seed_offset=0):
    model = mujoco.MjModel.from_xml_path(MODEL_PATH)
    data = mujoco.MjData(model)
    randomizer = DomainRandomizer(model, RANDOMIZATION_CFG)

    renderers = {name: mujoco.Renderer(model, height=h, width=w)
                 for name, (w, h) in CAMERA_SPECS.items()}

    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        fps=FPS,
        features=build_features(),
        root=root,
        robot_type="dual_so101",
        use_videos=True,
    )

    # Precompute body IDs once -- identical for every episode since the model
    # is not rebuilt.
    left_gripper_bodies = {
        model.body("left_gripper").id,
        model.body("left_moving_jaw_so101_v1").id,
    }
    plate_bid = model.body("plate").id

    seed_rng = np.random.RandomState(seed_offset)
    used_seeds = []

    for ep in range(n_episodes):
        seed = randomizer.sample_training_seed(seed_rng)
        assert not randomizer.is_eval_seed(seed), (
            f"sampled seed {seed} collides with a reserved eval seed"
        )
        used_seeds.append(seed)

        randomizer.reset(data, seed)
        mujoco.mj_forward(model, data)

        print(f"[collect] building IK trajectory for seed={seed}...")
        qpos_trace, gripper_trace, grasp_events = build_drawer_and_cutlery_episode(
            model, data, randomizer
        )

        # Locate the plate release step for THIS episode's gripper_trace.
        plate_open_step = _find_plate_release_step(gripper_trace)

        # Weld fires on first physical contact between a left-gripper body
        # and the plate -- the exact same trigger test_phases.py uses. The
        # armed flag is per-episode.
        plate_weld_armed = True

        print(f"[collect] trajectory: {len(qpos_trace)} steps, "
              f"cutlery-in-drawer={sorted(randomizer.last_in_drawer_items)}, "
              f"plate_release_step={plate_open_step}")

        for step_idx in range(len(qpos_trace)):
            _apply_qpos_to_ctrl(model, data, qpos_trace[step_idx])

            # Gripper commands carry an explicit side (left/right) now, since
            # bimanual phases use one arm to hold the drawer while the other
            # reaches -- a single hardcoded right_gripper write would leave
            # the left gripper uncommanded during its own retrieve phase.
            gval = gripper_trace[step_idx]
            if gval is not None:
                side, val = gval
                data.ctrl[model.actuator(f"{side}_gripper").id] = val

            # --- Right arm: drawer handle connect ------------------------
            if step_idx == grasp_events["activate_step"]:
                handle_world_now = data.geom_xpos[model.geom("drawer_handle").id].copy()
                activate_grasp_connect(model, data, grasp_events["eq_name"],
                                        grasp_events["body1"], grasp_events["body2"],
                                        handle_world_now)
            if step_idx == grasp_events["deactivate_step"]:
                deactivate_grasp_connect(model, data, grasp_events["eq_name"])

            # --- Left arm: plate WELD, on first contact ------------------
            # The moving jaw's convex-hull collision cannot retain a flat
            # plate under load (verified -- the plate slips out sideways).
            # A 6-DOF weld locks plate to left_gripper the instant fingers
            # touch it, using the same mechanism as the drawer handle but
            # with weld instead of connect (plate is a free 6-DOF body, not
            # on a slide).
            if plate_weld_armed:
                for c in range(data.ncon):
                    con = data.contact[c]
                    b1 = int(model.geom_bodyid[con.geom1])
                    b2 = int(model.geom_bodyid[con.geom2])
                    if ((b1 in left_gripper_bodies and b2 == plate_bid)
                            or (b2 in left_gripper_bodies and b1 == plate_bid)):
                        activate_grasp_weld(model, data, "left_grasp_weld",
                                             "left_gripper", "plate")
                        plate_weld_armed = False
                        break

            if plate_open_step is not None and step_idx == plate_open_step:
                deactivate_grasp_weld(model, data, "left_grasp_weld")

            for _ in range(control_decimation):
                mujoco.mj_step(model, data)

            if step_idx % RENDER_EVERY_N_STEPS != 0:
                continue

            state = get_joint_state(model, data)
            frames = render_all_cameras(renderers, data)
            frame = {
                "action": data.ctrl.copy()[: len(ACTUATOR_NAMES)].astype(np.float32),
                "observation.state": state,
                "task": instruction,
            }
            for cam_name, img in frames.items():
                frame[f"observation.images.{cam_name}"] = img
            dataset.add_frame(frame)

        dataset.save_episode()
        print(f"[collect] episode {ep+1}/{n_episodes} recorded (seed={seed})")

    dataset.finalize()
    print(f"\nWrote {n_episodes} episodes to {root}")
    print(f"Training seeds used (first 10 shown): {used_seeds[:10]}"
          + (" ..." if len(used_seeds) > 10 else ""))
    return dataset


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", type=int, default=3)
    parser.add_argument("--repo-id", type=str, default="local/dinner_table_ik")
    parser.add_argument("--root", type=str, default="./data/demo_dataset")
    parser.add_argument("--instruction", type=str,
                         default="open the drawer, retrieve the cutlery, close the drawer, set the table")
    parser.add_argument("--seed-offset", type=int, default=0)
    args = parser.parse_args()

    collect(args.episodes, args.repo_id, args.root, args.instruction,
             seed_offset=args.seed_offset)